services:
- type: web
  name: mbh-wordpress
  env: docker
  plan: starter
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 10
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: mbh-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: mbh-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: mbh-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: mbh-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: mbh-mysql
  repo: https://github.com/rhickey94/mysql.git
  env: docker
  plan: starter
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - key: MYSQL_DATABASE
    value: my_database
  - key: MYSQL_USER
    value: mysql
